import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, FileText } from 'lucide-react';
import { AnswerOption, SimuladoData } from '../types';

export function ExamReader({ simulado, index, onNavigate, onAnswer }: { simulado: SimuladoData; index: number; onNavigate: (index:number)=>void; onAnswer:(index:number,answer:AnswerOption)=>void }) {
  const [pdf, setPdf] = useState<File | null>(null);
  const [url, setUrl] = useState('');
  useEffect(()=>{ if(!pdf){setUrl('');return;}const next=URL.createObjectURL(pdf);setUrl(next);return()=>URL.revokeObjectURL(next);},[pdf]);
  const question=simulado.extractedQuestions?.find(item=>item.number===index+1);
  return <section className="exam-reader rounded-2xl border p-4 sm:p-5 mb-5 space-y-4">
    <div className="flex items-center justify-between gap-3 flex-wrap"><div className="flex items-center gap-2"><FileText className="w-5 h-5"/><div><h2 className="font-bold">Questões do PDF</h2><p className="text-xs opacity-70">{simulado.sourceFileName} · transcrição conferida</p></div></div><div className="flex items-center gap-2"><button aria-label="Questão anterior do PDF" className="secondary-action" disabled={index===0} onClick={()=>onNavigate(index-1)}><ChevronLeft className="w-4 h-4"/></button><span className="text-sm">{index+1} / {simulado.totalQuestions}</span><button aria-label="Próxima questão do PDF" className="secondary-action" disabled={index>=simulado.totalQuestions-1} onClick={()=>onNavigate(index+1)}><ChevronRight className="w-4 h-4"/></button></div></div>
    {question ? <><p className="text-xs opacity-70">{question.subject}{question.page ? ` · página ${question.page}`:''}</p><p className="whitespace-pre-wrap leading-relaxed text-sm sm:text-base">{question.statement}</p><div className="space-y-2">{(simulado.examType==='true_false' ? [{label:'V' as const,text:'Certo'},{label:'F' as const,text:'Errado'}] : question.options).map(option=><button key={option.label} className={`reader-option w-full text-left flex gap-3 rounded-xl border p-3 ${simulado.userAnswers[index]===option.label?'ai-selected':''}`} disabled={Boolean(simulado.isCorrected&&simulado.isLocked)} aria-pressed={simulado.userAnswers[index]===option.label} onClick={()=>onAnswer(index,option.label)}><strong>{option.label}</strong><span className="whitespace-pre-wrap text-sm">{option.text}</span></button>)}</div></> : <p className="text-sm">Esta questão não foi transcrita. Consulte o PDF original e marque a resposta no cartão.</p>}
    <details className="border-t pt-3"><summary className="text-sm cursor-pointer font-semibold">Consultar PDF original neste dispositivo</summary><p className="text-xs opacity-70 my-3">Selecione o arquivo original para conferir figuras, tabelas e fórmulas. Este arquivo fica somente nesta tela; os enunciados transcritos acompanham a prova e o backup.</p><input aria-label="Abrir PDF original da prova" type="file" accept="application/pdf" className="text-sm max-w-full" onChange={e=>{const file=e.target.files?.[0];if(file?.type==='application/pdf')setPdf(file);e.target.value='';}}/>{url&&<iframe title="Visualizador do PDF original" src={`${url}#page=${question?.page||1}`} sandbox="allow-same-origin" className="w-full h-[600px] mt-3 rounded-xl border"/>}</details>
  </section>;
}
